# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Darisee's INLS 161 Project
email: dariseejr@live.com
description: The Liberal Jekyll Theme
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dariseejr.github.io/" # the base hostname & protocol for your site
twitter_username: ninjadlp
github_username:  dariseejr

# Build settings
markdown: kramdown
